In [55]:
import random
from math import exp
from random import seed
import pandas as pd
import numpy as np

In [200]:
data = pd.read_csv("car.csv",names=["buying", "maint", "doors", "persons", "lug_boot", "safety", "decision"])

In [201]:
data.head()

buying  maint doors persons lug_boot safety decision
0  vhigh  vhigh     2       2    small    low    unacc
1  vhigh  vhigh     2       2    small    med    unacc
2  vhigh  vhigh     2       2    small   high    unacc
3  vhigh  vhigh     2       2      med    low    unacc
4  vhigh  vhigh     2       2      med    med    unacc

In [179]:
if __name__ == "__main__":
    
    dataset_name = "mushroom"
    
    if dataset_name == "car":
        data = pd.read_csv("car.csv", names=["buying", "maint", "doors", "persons", "lug_boot", "safety", "decision"])

        

        #inplace=True modifies the real df
        data["buying"].replace(["vhigh", "high", "med", "low"], [4, 3, 2, 1], inplace=True)
        data["maint"].replace(["vhigh", "high", "med", "low"], [4, 3, 2, 1], inplace=True)
        data["doors"].replace(["2", "3", "4", "5more"], [2, 3, 4, 6], inplace=True)
        data["persons"].replace(["2", "4", "more"], [2, 4, 5], inplace=True)
        data["lug_boot"].replace(["small", "med", "big"], [0, 1, 2], inplace=True)
        data["safety"].replace(["low", "med", "high"], [0, 1, 2], inplace=True)
        data["decision"].replace(["unacc", "acc", "good", "vgood"], [0, 1, 2, 3], inplace=True)

        #typecast all features and target values to int
        data.astype(int).dtypes
        
        
        
    
    elif dataset_name == "breastcancer":
        
         #breastcancer dataset
        data = pd.read_csv("breastcancer.csv", names=["codeNo", "clumpThickness", "uniCellSize", "uniCellShape", "mAdhesion", "sEpiCellSize", "bNuclei", "blandChromatin", "normalNucleoli", "mitoses", "decision"])
        

        data = data.drop("codeNo", axis="columns") # drop column sampleCodeNo(index)
        data = data.replace("?", np.NaN) #replace missing value to NaN
        data = data.dropna() #drop missing value

        #typecast all features and target values to int
        data.astype(int).dtypes
        data = data.astype({'bNuclei':'int'}) #convert float to int
        

        
        
    elif dataset_name == "ecoli":
        #ecoli dataset
        data = pd.read_csv("ecoli.csv", names=["seqName", "mcg", "gvh", "lip", "chg", "aac", "alm1", "alm2", "decision"],  delim_whitespace=True)
        

        data = data.drop("seqName", axis="columns")
        data["decision"].replace(["cp", "im", "imU", "imS", "imL", "om", "omL", "pp"], [0, 1, 2, 3, 4, 5, 6, 7], inplace=True)
        
        #convert float to int
        data = data.astype({'mcg': int, 'gvh': int, 'lip': int, 'chg': int, 'aac': int, 'alm1': int, 'alm2': int })
        data = data.astype({'decision':'int'}) #convert float to int
        

        
    elif dataset_name == "mushroom":
        #mushroom dataset
        data = pd.read_csv("mushroom.csv", names=["decision", "cap-shape", "cap-surface", "cap-color", "bruises", "odor",  "gill-attachment",
                                                                 "gill-spacing", "gill-size", "gill-color", "stalk-shape", "stalk-root", "stalk-surface-above-ring", "stalk-surface-below-ring",
                                                                 "stalk-color-above-ring", "stalk-color-below-ring", "veil-type", "veil-color", "ring-number", "ring-type", "spore-print-color",
                                                                 "population", "habitat"])
       
        data["decision"].replace(["e", "p"], [0, 1], inplace=True)
        data["cap-shape"].replace(["b", "c", "x", "f", "k", "s"], [0, 1, 2, 3, 4, 5], inplace=True)
        data["cap-surface"].replace(["f", "g", "y", "s"], [0, 1, 2, 3], inplace=True)
        data["cap-color"].replace(["n", "b", "c", "g", "r", "p", "u", "e", "w", "y"], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)
        data["bruises"].replace(["t", "f"], [0, 1], inplace=True)
        data["odor"].replace(["a", "l", "c", "y", "f", "m", "n", "p", "s"], [1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)
        data["gill-attachment"].replace(["a","d", "f", "n"], [0, 1, 2, 3], inplace=True)
        data["gill-spacing"].replace(["c", "w", "d"], [0, 1, 2], inplace=True)
        data["gill-size"].replace(["b", "n"], [0, 1], inplace=True)
        data["gill-color"].replace(["k", "n", "b", "h", "g", "r", "o", "p", "u", "e", "w", "y"], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], inplace=True)
        data["stalk-shape"].replace(["e", "t"], [0, 1], inplace=True)
        data["stalk-root"].replace(["b", "c", "u", "e","z", "r", "?"], [1, 2, 3, 4, 5, 6, 0], inplace=True)
        data["stalk-surface-above-ring"].replace(["f", "y", "k", "s"], [1, 2, 3, 4], inplace=True)
        data["stalk-surface-below-ring"].replace(["f", "y", "k", "s"], [1, 2, 3, 4], inplace=True)
        data["stalk-color-above-ring"].replace(["n", "b", "c", "g", "o", "p", "e", "w", "y"], [1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)
        data["stalk-color-below-ring"].replace(["n", "b", "c", "g", "o", "p", "e", "w", "y"], [1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)
        data["veil-type"].replace(["p", "u"], [1, 2], inplace=True)
        data["veil-color"].replace(["n", "o","w", "y"], [1, 2, 3, 4], inplace=True)
        data["ring-number"].replace(["n", "o", "t"],[1, 2, 3], inplace=True)
        data["ring-type"].replace(["c", "e", "f", "l", "n", "p", "s", "z"], [1, 2, 3, 4, 5, 6, 7, 8], inplace=True)
        data["spore-print-color"].replace(["k", "n", "b", "h", "r", "o", "u", "w", "y"], [1, 2, 3, 4, 5, 6, 7, 8, 9], inplace=True)
        data["population"].replace(["a", "c", "n", "s", "v", "y"], [1, 2, 3, 4, 5, 6], inplace=True)
        data["habitat"].replace(["g", "l", "m", "p", "u", "w", "d"], [1, 2, 3, 4, 5, 6, 7], inplace=True)
        
        #typecast all features and target values to int
        data.astype(int).dtypes
        # print(mushroom_df.dtypes)
        
         # Change coloumn order. Moving the decision column to the end
        data = data[["cap-shape", "cap-surface", "cap-color", "bruises", "odor",  "gill-attachment",
                             "gill-spacing", "gill-size", "gill-color", "stalk-shape", "stalk-root", "stalk-surface-above-ring", "stalk-surface-below-ring",
                             "stalk-color-above-ring", "stalk-color-below-ring", "veil-type", "veil-color", "ring-number", "ring-type", "spore-print-color",
                             "population", "habitat", "decision"]]
       
        # print('values', mushroom_df.values)
       

       
    elif dataset_name == "letter_recognition":
       
        data = pd.read_csv("letterrecognition.csv", names=["decision", "x-box", "y-box", "boxWidth", "boxHeight", "totalOnPixels",
                                        "x-bar", "y-bar", "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege", "xegvy", "y-ege", "yegvx"])


        data["decision"].replace(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"], [
                                              1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26], inplace=True)
       
        data.astype(int).dtypes
        # Change coloumn order. Moving the decision column to the end
        data = data[["x-box", "y-box", "boxWidth", "boxHeight", "totalOnPixels", "x-bar", "y-bar",
                                               "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege", "xegvy", "y-ege", "yegvx", "decision"]]

       
    else:
        print("Invalid Dataset")
        
#     accuracyList = []
#     for i in range(10):
#         accuracy = nbModelFit(input_dataFrame.values, nbClassifier, len(input_dataFrame.columns) - 1)
#         accuracyList.append(np.mean(accuracy))
        
#     mean_accuracy = np.sum(accuracyList)/len(accuracyList)
#     print('Naive Bayes Classification accuracy for %s dataset : %.3f%%' %(dataset_name, mean_accuracy))
#     std_dev = np.std(mean_accuracy)
#     print('stdv', np.std(mean_accuracy))
#     print("Naive Bayes Classification standard deviation for %s dataset : %.5f" %(dataset_name, std_dev))

In [180]:
data.head()

cap-shape  cap-surface  cap-color  bruises  odor gill-attachment  \
0          2            3          0        0     8               2   
1          2            3          9        0     1               2   
2          0            3          8        0     2               2   
3          2            2          8        0     8               2   
4          2            3          3        1     7               2   

  gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0            0          1           0            0  ...   
1            0          0           0            0  ...   
2            0          0           1            0  ...   
3            0          1           1            0  ...   
4            1          0           0            1  ...   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       8                       8          1           3   
1                       8                       8          1           3   
2                       8                       8          1           3   
3                       8                       8          1           3   
4                       8                       8          1           3   

   ring-number ring-type  spore-print-color  population habitat  decision  
0            2         6                  1           4       5         1  
1            2         6                  2           3       1         0  
2            2         6                  2           3       3         0  
3            2         6                  1           4       5         1  
4            2         2                  2           1       1         0  

[5 rows x 23 columns]

In [181]:
from sklearn.model_selection import StratifiedKFold

for i in range(10):

    data["kfold"] = -1

    print(data.head())

    data = data.sample(frac=1).reset_index(drop=True)
    kf = StratifiedKFold(n_splits=5, shuffle=True)

    for folds, (train_idx, test_idx) in enumerate(
           kf.split(X=data, y=data.decision.values)):
    
           print("train_idx : ", len(train_idx), "test_idx :", len(test_idx))
           data.loc[test_idx, "kfold"] = folds

data.to_csv("ANN/ctrain_folds.csv", index=False)


   cap-shape  cap-surface  cap-color  bruises  odor gill-attachment  \
0          2            3          0        0     8               2   
1          2            3          9        0     1               2   
2          0            3          8        0     2               2   
3          2            2          8        0     8               2   
4          2            3          3        1     7               2   

  gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0            0          1           0            0  ...   
1            0          0           0            0  ...   
2            0          0           1            0  ...   
3            0          1           1            0  ...   
4            1          0           0            1  ...   

   stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                       8          1           3            2          6   
1                       8          1           3            2     

In [182]:
new_df = pd.read_csv("ANN/ctrain_folds.csv")

In [183]:
new_df.head()

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0          3            2          9        1     5                2   
1          2            3          3        1     3                2   
2          2            2          3        0     7                2   
3          2            2          7        1     4                2   
4          3            0          3        0     7                2   

   gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0             0          0           4            0  ...   
1             0          1           4            0  ...   
2             0          0           1            1  ...   
3             0          1           2            1  ...   
4             0          0           7            1  ...   

   stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                       2          1           3            2          4   
1                       8          1           3            2          6   
2                       4          1           3            2          6   
3                       8          1           3            2          2   
4                       8          1           3            2          6   

   spore-print-color  population  habitat  decision  kfold  
0                  4           6        1         1      0  
1                  1           4        7         1      0  
2                  1           6        7         0      1  
3                  8           5        4         1      0  
4                  1           5        7         0      0  

[5 rows x 24 columns]

In [184]:
train_df = new_df[(new_df['kfold'] == 0) | (new_df['kfold'] == 1) | (new_df['kfold'] == 2) | (new_df['kfold'] == 3)]
test_df = new_df[(new_df['kfold']==4)]
train_df.to_numpy()

array([[3, 2, 9, ..., 1, 1, 0],
       [2, 3, 3, ..., 7, 1, 0],
       [2, 2, 3, ..., 7, 0, 1],
       ...,
       [2, 3, 0, ..., 2, 1, 3],
       [3, 0, 3, ..., 7, 0, 0],
       [2, 3, 8, ..., 1, 0, 3]], dtype=int64)

In [185]:
arr_new_df = new_df.to_numpy()
arr_train_df = train_df.to_numpy()
arr_test_df = test_df.to_numpy()

In [186]:
# Initializing an ANN network

def initializing_network(nn_inputs, nn_hidden, nn_outputs):
    n_network = list()
    n_hidden_layer = [{'weights':[random.uniform(-0.5,0.5) 
                                  for i in range(nn_inputs + 1)]} 
                      for i in range(nn_hidden)]
    n_network.append(n_hidden_layer)
    n_output_layer = [{'weights':[random.uniform(-0.5,0.5)
                                  for i in range(nn_hidden + 1)]} 
                      for i in range(nn_outputs)]
    n_network.append(n_output_layer)
    i= 1
    print("\n The initialised Neural Network:\n")
    for layer in n_network:
        j=1
        for sub in layer:
            print("\n Layer[%d] Node[%d]:\n" %(i,j),sub)
            j=j+1
        i=i+1
    return n_network

In [187]:
# Calculating neuron activation for an input

def neuron_activate(weights, inputs):
    neuron_activation = weights[-1]
    for i in range(len(weights)-1):
        neuron_activation += weights[i] * inputs[i]
    return neuron_activation

In [188]:
# Transfering neuron activation to sigmoid function 
def neuron_transfer(activation_function):
    return 1.0 / (1.0 + exp(-activation_function))

In [189]:
# Forward propagating input to a network's output
def forward_propagation(n_network, row):
    inputs = row
    for layer in n_network:
        new_inputs = []
        for neuron in layer:
            neuron_activation = neuron_activate(neuron['weights'], inputs)
            neuron['output'] = neuron_transfer(neuron_activation)
            new_inputs.append(neuron['output'])
        inputs = new_inputs
    return inputs

In [190]:
# Calculating the derivative of a neuron output
def transfering_derivative(output):
    return output * (1.0 - output)

In [191]:
# Backpropagating error and store in neurons
def backward_propagation_error(n_network, expected):
    for i in reversed(range(len(n_network))):
        layer = n_network[i]
        errors = list()
        
        if i != len(n_network)-1:
            for j in range(len(layer)):
                error = 0.0
                for neuron in n_network[i + 1]:
                    error += (neuron['weights'][j] * neuron['delta'])
                errors.append(error)
        else:
            for j in range(len(layer)):
                neuron = layer[j]
                errors.append(expected[j] - neuron['output'])
        
        for j in range(len(layer)):
            neuron = layer[j]
            neuron['delta'] = errors[j] * transfering_derivative(neuron['output'])
 

In [192]:
# Updating the network weights with error
def updating_weights(n_network, row, learning_rate):
    for i in range(len(n_network)):
        inputs = row[:-1]
        if i != 0:
            inputs = [neuron['output'] for neuron in n_network[i - 1]]
        for neuron in n_network[i]:
            for j in range(len(inputs)):
                neuron['weights'][j] += learning_rate * neuron['delta'] * inputs[j]
            neuron['weights'][-1] += learning_rate * neuron['delta']

In [193]:
# Training the network for a fixed number of epochs
def training_network(n_network, train, learning_rate, n_epoch, nn_outputs):
   
    print("\n Starting Network Training:\n")
    
    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            outputs = forward_propagation(n_network, row)
            expected = [0 for i in range(nn_outputs)]
            expected[row[-1]] = 1
            sum_error += sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
            backward_propagation_error(n_network, expected)
            updating_weights(n_network, row, learning_rate)
        print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, learning_rate, sum_error))
    
    print("\n Network Training done:\n")

In [194]:
print("\n The input Data Set :\n",arr_new_df)
nn_inputs = len(arr_new_df[0]) - 1
print("\n Number of Inputs :\n",nn_inputs)
#nn_outputs = car_data["decision"]
nn_outputs = len(set([row[-1] for row in arr_new_df]))
print("\n Number of Outputs :\n",nn_outputs)


 The input Data Set :
 [[3 2 9 ... 1 1 0]
 [2 3 3 ... 7 1 0]
 [2 2 3 ... 7 0 1]
 ...
 [3 0 3 ... 7 0 0]
 [2 3 8 ... 1 0 3]
 [2 3 9 ... 3 0 4]]

 Number of Inputs :
 23

 Number of Outputs :
 5


In [195]:
#Network Initialization
n_network = initializing_network(nn_inputs,20, nn_outputs)


 The initialised Neural Network:


 Layer[1] Node[1]:
 {'weights': [0.3035166251859074, 0.15164141080544447, -0.2573947969641296, -0.33728709360887765, 0.14024531634210646, 0.027410215713522867, -0.11679204449297464, -0.04142139848827131, 0.14936312940327146, -0.49177022570450724, 0.42306485463875876, -0.3003765637413901, 0.14227321424154882, -0.13230103867706045, -0.23294136040794988, -0.4761813778828009, 0.4044901793670501, -0.44405732351263616, -0.09250274670210246, -0.4640505567202473, 0.3243260371351312, -0.35827885479731225, -0.07336803677128556, 0.4349488332026228]}

 Layer[1] Node[2]:
 {'weights': [-0.022742699694495272, 0.0759116527060254, 0.2555065636310463, -0.2914958231666397, -0.3869588529483664, 0.34933746771248364, 0.24407762196940241, 0.34167067958697994, -0.07066893498064408, -0.423504995969482, -0.3174588152347946, 0.05137077521395261, 0.18369084086108, 0.47837687577019816, 0.1860174796984928, 0.2609483472476336, 0.30048314371855767, -0.05211228362487119, -0.26352888

In [196]:
# Training the Network
training_network(n_network, arr_train_df, 1, 10, nn_outputs)



 Starting Network Training:

>epoch=0, lrate=1.000, error=5088.660
>epoch=1, lrate=1.000, error=4968.847
>epoch=2, lrate=1.000, error=4960.044
>epoch=3, lrate=1.000, error=4959.389
>epoch=4, lrate=1.000, error=4959.273
>epoch=5, lrate=1.000, error=4961.773
>epoch=6, lrate=1.000, error=4993.739
>epoch=7, lrate=1.000, error=5040.251
>epoch=8, lrate=1.000, error=5040.379
>epoch=9, lrate=1.000, error=5018.741

 Network Training done:



In [197]:
i= 1
for layer in n_network:
    j=1
    for sub in layer:
        print("\n Layer[%d] Node[%d]:\n" %(i,j),sub)
        j=j+1
    i=i+1


 Layer[1] Node[1]:
 {'weights': [0.19473563248818368, 0.07125758903642912, -0.36996225181725423, -0.35608910998381954, -0.059438572609439015, -0.029530056597711154, -0.12513159942193572, -0.04029099876270373, -0.04938561857349731, -0.4979422362578798, 0.3367301582942613, -0.41029742097822197, 0.048470240374272854, -0.2714695907446545, -0.38382141578590917, -0.5102629225760674, 0.3061141937274454, -0.5080931478299503, -0.26009690461263535, -0.5266518559707, 0.17014565236987103, -0.46258137234470775, -0.08766887475092738, 0.400867288509351], 'output': 9.58148225191008e-05, 'delta': 2.384801189380594e-06}

 Layer[1] Node[2]:
 {'weights': [-0.05362698048627601, -0.03449879711826728, -0.1811139071934858, -0.2986991798926266, -0.5099690356986837, 0.27519678983047263, 0.26014340572672456, 0.3183897571081344, -0.30769283767154093, -0.40147418879696806, -0.3490171643510544, -0.1237981366572617, 0.021173261155706377, 0.3029025535100186, -0.006111558452501533, 0.22353189282521446, 0.188741378304

In [198]:
from math import exp

# Calculating neuron activation for an input
def neuron_activate(weights, inputs):
    neuron_activation = weights[-1]
    for i in range(len(weights)-1):
        neuron_activation += weights[i] * inputs[i]
    return neuron_activation

In [199]:
# Transfer neuron activation
def neuron_transfer(activation_function):
    return 1.0 / (1.0 + exp(-activation_function))

In [200]:
# Forward propagating a input to a network output
def forward_propagation(n_network, row):
    inputs = row
    for layer in n_network:
        new_inputs = []
        for neuron in layer:
            neuron_activation = neuron_activate(neuron['weights'], inputs)
            neuron['output'] = neuron_transfer(neuron_activation)
            new_inputs.append(neuron['output'])
        inputs = new_inputs
    return inputs

In [201]:
# Make a prediction with a network
def predict(n_network, row):
    outputs = forward_propagation(n_network, row)
    return outputs.index(max(outputs))

In [202]:
for row in arr_train_df:
    prediction = predict(n_network, row)
    print('Actual Expected Value=%d, Obtained Results=%d' % (row[-1], prediction))
    

Actual Expected Value=0, Obtained Results=0
Actual Expected Value=0, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=0, Obtained Results=0
Actual Expected Value=0, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=2, Obtained Results=0
Actual Expected Value=2, Obtained Results=0
Actual Expected Value=0, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=1, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=0, Obtained Results=0
Actual Expected Value=3, Obtained Results=0
Actual Expected Value=0, Obtaine

In [204]:
correct_instances = 0
for row in arr_train_df:
    prediction = predict(n_network, row)
    if row[-1] == prediction:
        correct_instances += 1
        #np.std(correct_instances)
ann_accuracy = correct_instances / float(len(arr_train_df));
print('Accuracy of our predicted ANN:', ann_accuracy * 100)
print("Standard Deviation of ANN: %.5f " % np.std(row/correct_instances))

Accuracy of our predicted ANN: 25.01538461538462
Standard Deviation of ANN: 0.00152 
